CREATE OR REPLACE TABLE `kramp-sharedmasterdata-prd.MadsH.purchase_data_enriched` AS
-- 1) Filter and stage attribute rows
WITH attributes_raw AS (
  SELECT
    AttributeID,
    ItemNumber,
    LOVID,
    LanguageID,
    UnitID,
    value
  FROM
    `kramp-sharedmasterdata-prd.kramp_sharedmasterdata_customquery.TBL__CMQ__assortment__varga__12_golden_item_technical_attribute_value`
  WHERE
    LanguageID = 'ENG'
    AND AttributeID IN (
      'taConnectionType_6',
      'taForStrapBolt',
      'taHeadShape',
      'taHeadType',
      'taLabelColourCode',
      'taMaterial',
      'taMaterial_2',
      'taMaterial_40',
      'taMaterial_46',
      'taMaterial_47',
      'taMaterial_7',
      'taMaterial_9',
      'taMeasurementsType',
      'taSurfaceThreatment',
      'taSurfaceThreatment_11',
      'taSurfaceTreatment_13',
      'taSurfaceTreatment_17',
      'taSurfaceTreatment_4',
      'taSurfaceTreatment_5',
      'taThreadDirection_',
      'taThreadType_',
      'taThreadType_10',
      'taThreadType_4',
      'taThreadType_9',
      'taType_22'
    )
),

-- 2) Join purchase_data with attributes
joined AS (
  SELECT
    p.*,
    a.AttributeID,
    a.value AS AttributeValue
  FROM `kramp-sharedmasterdata-prd.MadsH.purchase_data` AS p
  LEFT JOIN attributes_raw AS a
    ON SAFE_CAST(p.ProductNumber AS STRING) = SAFE_CAST(a.ItemNumber AS STRING)
),

-- 3) Normalize AttributeID to clean attribute key
normalized AS (
  SELECT
    year_authorization,
    uniquevendorcode,
    warehouse,
    ProductNumber,
    ProductDescription,
    purchase_amount_eur,
    purchase_quantity,
    crm_main_vendor,
    crm_main_group_vendor,
    class2,
    class3,
    class4,
    brandName,
    BrandType,
    assortmentType,
    level0,
    level1,
    level2,
    level3,
    level4,
    countryOfOrigin,
    category_manager,
    supplier_group,
    procurement_bu,
    supplier_site_name,
    supplier_site_status,
    supplier_profile,
    supplier_profile_status,
    supplier_parent,
    alternate_site_name,
    procurement_manager,
    supplier_manager,
    supplier_specialist,
    inventory_specialist,
    purchase_order_specialist,
    abc_code,
    category,
    dutch_windmill,
    supplier_site_payment_terms,
    supplier_site_delivery_conditions,
    supplier_site_country,
    supplier_site_city,
    crm_vendor,
    crm_group_vendor,
    PLMStatusGlobal,
    EAN_code,
    cn_code,
    contract_type,
    key_brand_identifier,
    PurchaseStopInd,
    salesRounding,

    -- normalized attribute key
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(AttributeID, r'^ta', ''),   -- drop 'ta'
        r'_[0-9]+$', ''                            -- drop numeric suffix _x
      ),
      r'_$', ''                                    -- drop trailing underscore
    ) AS attr_key,

    AttributeValue
  FROM joined
),

-- 4) Aggregate distinct values per row+attr_key (remove duplicates)
attr_agg AS (
  SELECT
    year_authorization,
    uniquevendorcode,
    warehouse,
    ProductNumber,
    ProductDescription,
    purchase_amount_eur,
    purchase_quantity,
    crm_main_vendor,
    crm_main_group_vendor,
    class2,
    class3,
    class4,
    brandName,
    BrandType,
    assortmentType,
    level0,
    level1,
    level2,
    level3,
    level4,
    countryOfOrigin,
    category_manager,
    supplier_group,
    procurement_bu,
    supplier_site_name,
    supplier_site_status,
    supplier_profile,
    supplier_profile_status,
    supplier_parent,
    alternate_site_name,
    procurement_manager,
    supplier_manager,
    supplier_specialist,
    inventory_specialist,
    purchase_order_specialist,
    abc_code,
    category,
    dutch_windmill,
    supplier_site_payment_terms,
    supplier_site_delivery_conditions,
    supplier_site_country,
    supplier_site_city,
    crm_vendor,
    crm_group_vendor,
    PLMStatusGlobal,
    EAN_code,
    cn_code,
    contract_type,
    key_brand_identifier,
    PurchaseStopInd,
    salesRounding,
    attr_key,

    ARRAY_TO_STRING(
      ARRAY_AGG(DISTINCT AttributeValue IGNORE NULLS ORDER BY AttributeValue),
      ' | '
    ) AS AttributeValue_agg

  FROM normalized
  GROUP BY
    year_authorization,
    uniquevendorcode,
    warehouse,
    ProductNumber,
    ProductDescription,
    purchase_amount_eur,
    purchase_quantity,
    crm_main_vendor,
    crm_main_group_vendor,
    class2,
    class3,
    class4,
    brandName,
    BrandType,
    assortmentType,
    level0,
    level1,
    level2,
    level3,
    level4,
    countryOfOrigin,
    category_manager,
    supplier_group,
    procurement_bu,
    supplier_site_name,
    supplier_site_status,
    supplier_profile,
    supplier_profile_status,
    supplier_parent,
    alternate_site_name,
    procurement_manager,
    supplier_manager,
    supplier_specialist,
    inventory_specialist,
    purchase_order_specialist,
    abc_code,
    category,
    dutch_windmill,
    supplier_site_payment_terms,
    supplier_site_delivery_conditions,
    supplier_site_country,
    supplier_site_city,
    crm_vendor,
    crm_group_vendor,
    PLMStatusGlobal,
    EAN_code,
    cn_code,
    contract_type,
    key_brand_identifier,
    PurchaseStopInd,
    salesRounding,
    attr_key
)

-- 5) Final wide table (SurfaceThreatment merged into SurfaceTreatment)
SELECT
  year_authorization,
  uniquevendorcode,
  warehouse,
  ProductNumber,
  ProductDescription,
  purchase_amount_eur,
  purchase_quantity,
  crm_main_vendor,
  crm_main_group_vendor,
  class2,
  class3,
  class4,
  brandName,
  BrandType,
  assortmentType,
  level0,
  level1,
  level2,
  level3,
  level4,
  countryOfOrigin,
  category_manager,
  supplier_group,
  procurement_bu,
  supplier_site_name,
  supplier_site_status,
  supplier_profile,
  supplier_profile_status,
  supplier_parent,
  alternate_site_name,
  procurement_manager,
  supplier_manager,
  supplier_specialist,
  inventory_specialist,
  purchase_order_specialist,
  abc_code,
  category,
  dutch_windmill,
  supplier_site_payment_terms,
  supplier_site_delivery_conditions,
  supplier_site_country,
  supplier_site_city,
  crm_vendor,
  crm_group_vendor,
  PLMStatusGlobal,
  EAN_code,
  cn_code,
  contract_type,
  key_brand_identifier,
  PurchaseStopInd,
  salesRounding,

  MAX(IF(attr_key = 'ConnectionType',    AttributeValue_agg, NULL)) AS ConnectionType,
  MAX(IF(attr_key = 'ForStrapBolt',      AttributeValue_agg, NULL)) AS ForStrapBolt,
  MAX(IF(attr_key = 'HeadShape',         AttributeValue_agg, NULL)) AS HeadShape,
  MAX(IF(attr_key = 'HeadType',          AttributeValue_agg, NULL)) AS HeadType,
  MAX(IF(attr_key = 'LabelColourCode',   AttributeValue_agg, NULL)) AS LabelColourCode,
  MAX(IF(attr_key = 'Material',          AttributeValue_agg, NULL)) AS Material,
  MAX(IF(attr_key = 'MeasurementsType',  AttributeValue_agg, NULL)) AS MeasurementsType,

  -- merged SurfaceTreatment (from both SurfaceTreatment + SurfaceThreatment keys)
  (
    CASE
      WHEN MAX(IF(attr_key = 'SurfaceTreatment',  AttributeValue_agg, NULL)) IS NOT NULL
           AND MAX(IF(attr_key = 'SurfaceThreatment', AttributeValue_agg, NULL)) IS NOT NULL
           AND MAX(IF(attr_key = 'SurfaceTreatment',  AttributeValue_agg, NULL))
               != MAX(IF(attr_key = 'SurfaceThreatment', AttributeValue_agg, NULL))
      THEN CONCAT(
        MAX(IF(attr_key = 'SurfaceTreatment',  AttributeValue_agg, NULL)),
        ' | ',
        MAX(IF(attr_key = 'SurfaceThreatment', AttributeValue_agg, NULL))
      )
      ELSE COALESCE(
        MAX(IF(attr_key = 'SurfaceTreatment',  AttributeValue_agg, NULL)),
        MAX(IF(attr_key = 'SurfaceThreatment', AttributeValue_agg, NULL))
      )
    END
  ) AS SurfaceTreatment,

  MAX(IF(attr_key = 'ThreadDirection',   AttributeValue_agg, NULL)) AS ThreadDirection,
  MAX(IF(attr_key = 'ThreadType',        AttributeValue_agg, NULL)) AS ThreadType,
  MAX(IF(attr_key = 'Type',              AttributeValue_agg, NULL)) AS Type

FROM attr_agg
GROUP BY
  year_authorization,
  uniquevendorcode,
  warehouse,
  ProductNumber,
  ProductDescription,
  purchase_amount_eur,
  purchase_quantity,
  crm_main_vendor,
  crm_main_group_vendor,
  class2,
  class3,
  class4,
  brandName,
  BrandType,
  assortmentType,
  level0,
  level1,
  level2,
  level3,
  level4,
  countryOfOrigin,
  category_manager,
  supplier_group,
  procurement_bu,
  supplier_site_name,
  supplier_site_status,
  supplier_profile,
  supplier_profile_status,
  supplier_parent,
  alternate_site_name,
  procurement_manager,
  supplier_manager,
  supplier_specialist,
  inventory_specialist,
  purchase_order_specialist,
  abc_code,
  category,
  dutch_windmill,
  supplier_site_payment_terms,
  supplier_site_delivery_conditions,
  supplier_site_country,
  supplier_site_city,
  crm_vendor,
  crm_group_vendor,
  PLMStatusGlobal,
  EAN_code,
  cn_code,
  contract_type,
  key_brand_identifier,
  PurchaseStopInd,
  salesRounding;
