-- If you want data for a specific Class2, change create_purchase_data.sql
-- Check brand filter in create_purchase_data.sql, default is 'kramp'
-- Check level2 filter in create_purchase_data.sql, default is 'Threaded Fasteners'
-- Create a combined table joining purchase and product data
CREATE OR REPLACE TABLE `kramp-sharedmasterdata-prd.MadsH.purchase_data_enriched` AS
SELECT
  -- purchase_data fields
  p.year_authorization,
  p.uniquevendorcode,
  p.warehouse,
  p.ProductNumber,
  p.ProductDescription,
  p.purchase_amount_eur,
  p.purchase_quantity,
  p.crm_main_vendor,
  p.crm_main_group_vendor,
  p.class2,
  p.class3,
  p.class4,
  p.brandName,
  p.BrandType,
  p.assortmentType,
  p.level0,
  p.level1,
  p.level2,
  p.level3,
  p.level4,
  p.countryOfOrigin,
  p.category_manager,

  -- product_data fields
  d.product_id,
  d.BrickID,
  d.unit,
  d.head_shape,
  d.thread_type,
  d.head_height,
  d.head_outside_diameter_width,
  d.quality,
  d.surface_treatment,
  d.material,
  d.din_standard,
  d.weight_per_100_pcs,
  d.content_in_sales_unit,
  d.thread_diameter,
  d.length,
  d.height,
  d.total_height,
  d.width,
  d.iso_standard,
  d.inside_diameter,
  d.outside_diameter,
  d.thickness,
  d.designed_for_thread,
  d.total_length,
  d.head_type,
  d.thread_length,

  -- additional purchase_data enrichment fields
  p.supplier_group,
  p.procurement_bu,
  p.supplier_site_name,
  p.supplier_site_status,
  p.supplier_profile,
  p.supplier_profile_status,
  p.supplier_parent,
  p.alternate_site_name,
  p.procurement_manager,
  p.supplier_manager,
  p.supplier_specialist,
  p.inventory_specialist,
  p.purchase_order_specialist,
  p.abc_code,
  p.category,
  p.dutch_windmill,
  p.supplier_site_payment_terms,
  p.supplier_site_delivery_conditions,
  p.supplier_site_country,
  p.supplier_site_city,
  p.crm_vendor,
  p.crm_group_vendor,
  p.PLMStatusGlobal,
  p.EAN_code,
  p.cn_code,
  p.contract_type,
  p.key_brand_identifier,
  p.PurchaseStopInd,
  p.salesRounding,

FROM `kramp-sharedmasterdata-prd.MadsH.purchase_data` AS p
LEFT JOIN `kramp-sharedmasterdata-prd.MadsH.product_data` AS d
  ON SAFE_CAST(p.ProductNumber AS STRING) = SAFE_CAST(d.ProductNumber AS STRING)
