-- 1) Recreate table (drop -> create to avoid spec conflicts)
DROP TABLE IF EXISTS `kramp-sharedmasterdata-prd.MadsH.tender_material`;

CREATE TABLE `kramp-sharedmasterdata-prd.MadsH.tender_material`
CLUSTER BY item_number, attribute_id
OPTIONS (
  description = "Selected product fields × Ciske attributes + STEP_CountryOfOrigin; item_number = COALESCE(pk_itemnumber, item_id)"
)
AS
WITH src_products AS (
  SELECT
    -- product columns (pk_itemnumber only used to derive item_number)
    pk_itemnumber,
    item_description,
    category,
    category_code,
    item_classification,
    class_2,
    class_3,
    class_4,
    class_4_id,
    creation_date,
    level0,
    level1,
    level2,
    level3,
    level4,
    item_type,
    countries_webshop_ind_active,
    count_countries_webshop_active,
    tag_webshop_active,
    stop_purchase_ind,
    brand_type,
    brand_name,
    brand_type_agg,
    brand_type_best_better_good,
    brand_type_ABC_brands,
    brand_type_ta24,
    turnover_eur_2021,
    turnover_eur_2022,
    turnover_eur_2023,
    turnover_eur_2024,
    orders_2021,
    orders_2022,
    orders_2023,
    orders_2024,
    tag_has_turnover,
    avg_order_value_eur_2021,
    avg_order_value_eur_2022,
    avg_order_value_eur_2023,
    avg_order_value_eur_2024,
    quantity_sold_2021,
    quantity_sold_2022,
    quantity_sold_2023,
    quantity_sold_2024,
    avg_price_eur_2021,
    avg_price_eur_2022,
    avg_price_eur_2023,
    avg_price_eur_2024,
    list_price_turnover_eur_2021,
    list_price_turnover_eur_2022,
    list_price_turnover_eur_2023,
    list_price_turnover_eur_2024,
    margin_gross_eur_2021,
    margin_gross_eur_2022,
    margin_gross_eur_2023,
    margin_gross_eur_2024,
    margin_gross_perc_2021,
    margin_gross_perc_2022,
    margin_gross_perc_2023,
    margin_gross_perc_2024,
    customers_total_2021,
    customers_total_2022,
    customers_total_2023,
    customers_total_2024,
    sold_to_customers_new_2021,
    sold_to_customers_new_2022,
    sold_to_customers_new_2023,
    sold_to_customers_new_2024,
    customers_repeat_2021,
    customers_repeat_2022,
    customers_repeat_2023,
    customers_repeat_2024,
    customer_ordered_multiple_times_2021,
    customer_ordered_multiple_times_2022,
    customer_ordered_multiple_times_2023,
    stock_on_hand_units,
    stock_on_hand_eur,
    warehouse_with_stock,
    count_warehouse_with_stock,
    supplier_count_id,
    supplier_name_string,
    supplier_code_string_best_abc,
    supplier_name_string_best_abc,
    supplier_relation_best_abc,
    supplier_kraljic_matrix_best_abc,
    supplier_abc_class_best_abc,
    supplier_euro_w_mix_best_abc,
    supplier_categories_bought_best_abc,
    purchase_amount_eur_2020,
    purchase_amount_eur_2021,
    purchase_amount_eur_2022,
    purchase_amount_eur_2023,
    purchase_amount_eur_2024,
    abc_costtotal_2021,
    abc_costdistributiontotal_2021,
    abc_costsalestotal_2021,
    abc_costtechnologytotal_2021,
    abc_profitability_2021,
    abc_profitabily_percentage_2021,
    abc_turnover_2021,
    abc_costofgoodssold_2021,
    abc_costtotal_2022,
    abc_costdistributiontotal_2022,
    abc_costsalestotal_2022,
    abc_costtechnologytotal_2022,
    abc_profitability_2022,
    abc_profitabily_percentage_2022,
    abc_turnover_2022,
    abc_costofgoodssold_2022,
    abc_costtotal_2023,
    abc_costdistributiontotal_2023,
    abc_costsalestotal_2023,
    abc_costtechnologytotal_2023,
    abc_profitability_2023,
    abc_profitabily_percentage_2023,
    abc_turnover_2023,
    abc_costofgoodssold_2023,
    abc_costtotal_2024,
    abc_costdistributiontotal_2024,
    abc_costsalestotal_2024,
    abc_costtechnologytotal_2024,
    abc_profitability_2024,
    abc_profitabily_percentage_2024,
    abc_turnover_2024,
    abc_costofgoodssold_2024,
    step_product_key,
    step_product_id,
    product_is_active
  FROM `kramp-sharedmasterdata-prd.kramp_sharedmasterdata_customquery.TBL__ProductManagment__CategoryAnalysisMachinery__TotalQuery`
),
src_attr AS (
  SELECT
    -- attribute columns (item_id only used to derive item_number)
    item_id,
    attribute_id,
    attribute_value_id,
    is_synthetic,
    attribute_data_type,
    attribute_description,
    locale_independent_values,
    localized_values,
    unit_of_measurement_symbol,
    unit_of_measurement_description,
    attribute_sort_order,
    attribute_value_sort_order
  FROM `kramp-sharedmasterdata-prd.kramp_sharedmasterdata_source.SRC__HUB__ciske_catalog_item_attributes`
),
src_origin AS (
  -- Use STEP_ItemNumber explicitly
  SELECT
    CAST(STEP_ItemNumber AS STRING) AS item_id,
    ANY_VALUE(STEP_CountryOfOrigin) AS STEP_CountryOfOrigin
  FROM `kramp-sharedmasterdata-prd.kramp_sharedmasterdata_customquery.CMQ__ItemSupplierData__Combined_v5`
  WHERE STEP_ItemNumber IS NOT NULL
  GROUP BY 1
)
SELECT
  -- unified key persisted
  COALESCE(CAST(p.pk_itemnumber AS STRING), CAST(a.item_id AS STRING)) AS item_number,

  -- product slice (pk_itemnumber NOT selected)
  p.item_description,
  p.category,
  p.category_code,
  p.item_classification,
  p.class_2,
  p.class_3,
  p.class_4,
  p.class_4_id,
  p.creation_date,
  p.level0,
  p.level1,
  p.level2,
  p.level3,
  p.level4,
  p.item_type,
  p.countries_webshop_ind_active,
  p.count_countries_webshop_active,
  p.tag_webshop_active,
  p.stop_purchase_ind,
  p.brand_type,
  p.brand_name,
  p.brand_type_agg,
  p.brand_type_best_better_good,
  p.brand_type_ABC_brands,
  p.brand_type_ta24,
  p.turnover_eur_2021,
  p.turnover_eur_2022,
  p.turnover_eur_2023,
  p.turnover_eur_2024,
  p.orders_2021,
  p.orders_2022,
  p.orders_2023,
  p.orders_2024,
  p.tag_has_turnover,
  p.avg_order_value_eur_2021,
  p.avg_order_value_eur_2022,
  p.avg_order_value_eur_2023,
  p.avg_order_value_eur_2024,
  p.quantity_sold_2021,
  p.quantity_sold_2022,
  p.quantity_sold_2023,
  p.quantity_sold_2024,
  p.avg_price_eur_2021,
  p.avg_price_eur_2022,
  p.avg_price_eur_2023,
  p.avg_price_eur_2024,
  p.list_price_turnover_eur_2021,
  p.list_price_turnover_eur_2022,
  p.list_price_turnover_eur_2023,
  p.list_price_turnover_eur_2024,
  p.margin_gross_eur_2021,
  p.margin_gross_eur_2022,
  p.margin_gross_eur_2023,
  p.margin_gross_eur_2024,
  p.margin_gross_perc_2021,
  p.margin_gross_perc_2022,
  p.margin_gross_perc_2023,
  p.margin_gross_perc_2024,
  p.customers_total_2021,
  p.customers_total_2022,
  p.customers_total_2023,
  p.customers_total_2024,
  p.sold_to_customers_new_2021,
  p.sold_to_customers_new_2022,
  p.sold_to_customers_new_2023,
  p.sold_to_customers_new_2024,
  p.customers_repeat_2021,
  p.customers_repeat_2022,
  p.customers_repeat_2023,
  p.customers_repeat_2024,
  p.customer_ordered_multiple_times_2021,
  p.customer_ordered_multiple_times_2022,
  p.customer_ordered_multiple_times_2023,
  p.stock_on_hand_units,
  p.stock_on_hand_eur,
  p.warehouse_with_stock,
  p.count_warehouse_with_stock,
  p.supplier_count_id,
  p.supplier_name_string,
  p.supplier_code_string_best_abc,
  p.supplier_name_string_best_abc,
  p.supplier_relation_best_abc,
  p.supplier_kraljic_matrix_best_abc,
  p.supplier_abc_class_best_abc,
  p.supplier_euro_w_mix_best_abc,
  p.supplier_categories_bought_best_abc,
  p.purchase_amount_eur_2020,
  p.purchase_amount_eur_2021,
  p.purchase_amount_eur_2022,
  p.purchase_amount_eur_2023,
  p.purchase_amount_eur_2024,
  p.abc_costtotal_2021,
  p.abc_costdistributiontotal_2021,
  p.abc_costsalestotal_2021,
  p.abc_costtechnologytotal_2021,
  p.abc_profitability_2021,
  p.abc_profitabily_percentage_2021,
  p.abc_turnover_2021,
  p.abc_costofgoodssold_2021,
  p.abc_costtotal_2022,
  p.abc_costdistributiontotal_2022,
  p.abc_costsalestotal_2022,
  p.abc_costtechnologytotal_2022,
  p.abc_profitability_2022,
  p.abc_profitabily_percentage_2022,
  p.abc_turnover_2022,
  p.abc_costofgoodssold_2022,
  p.abc_costtotal_2023,
  p.abc_costdistributiontotal_2023,
  p.abc_costsalestotal_2023,
  p.abc_costtechnologytotal_2023,
  p.abc_profitability_2023,
  p.abc_profitabily_percentage_2023,
  p.abc_turnover_2023,
  p.abc_costofgoodssold_2023,
  p.abc_costtotal_2024,
  p.abc_costdistributiontotal_2024,
  p.abc_costsalestotal_2024,
  p.abc_costtechnologytotal_2024,
  p.abc_profitability_2024,
  p.abc_profitabily_percentage_2024,
  p.abc_turnover_2024,
  p.abc_costofgoodssold_2024,
  p.step_product_key,
  p.step_product_id,
  p.product_is_active,

  -- attribute slice (item_id NOT selected)
  a.attribute_id,
  a.attribute_value_id,
  a.is_synthetic,
  a.attribute_data_type,
  a.attribute_description,
  a.locale_independent_values,
  a.localized_values,
  a.unit_of_measurement_symbol,
  a.unit_of_measurement_description,
  a.attribute_sort_order,
  a.attribute_value_sort_order,

  -- origin
  o.STEP_CountryOfOrigin

FROM src_products p
LEFT JOIN src_attr   a ON CAST(a.item_id AS STRING) = CAST(p.pk_itemnumber AS STRING)
LEFT JOIN src_origin o ON o.item_id = COALESCE(CAST(p.pk_itemnumber AS STRING), CAST(a.item_id AS STRING));
